site_name: rim_airflow_utils
site_url: https://yaerimkim.github.io/rim_airflow_utils
repo_url: https://github.com/yaerimkim/rim_airflow_utils
repo_name: yaerimkim/rim_airflow_utils

theme:
  logo: img/logo.png
  favicon: img/favicon-16x16.png
  name: "material"
  language: kr
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        primary: white
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - mermaid2:
      version: 8.6.4
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.progressbar
  - fontawesome_markdown

extra:
  analytics:
    provider: google
    property: 

extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js

nav:
  - 'Introduction': 'index.md'
  - 'rim_airflow_utils Docstring': docs.md
  - 'Issue Tracker': 'https://github.com/yaerimkim/rim_airflow_utils/issues'

